<?php
/**
 * Liebherr Interface Solutions – Handbuch (Admin-Seite)
 *
 * Handbuch-Regel (CLAUDE.md Abschnitt 1): letzter Reiter des Moduls, fortgeschrieben bei
 * jeder fachlichen Erweiterung. Deckt seit alpha.22 alle neun Boards (inkl. Content
 * Board, Kontaktanfragen und Partnerdokumente) sowie die sieben Frontend-Shortcodes und die Nachvollziehbarkeits-Reiter
 * (Programmierlogbuch, To-Dos) ab.
 *
 * @package Liebherr\InterfaceWorld\Admin\Pages
 * @since   0.1.0-alpha.1
 */

declare( strict_types = 1 );

namespace Liebherr\InterfaceWorld\Admin\Pages;

if ( ! defined( 'ABSPATH' ) ) { exit; }

final class HandbookPage {

	public static function render(): void {
		?>
		<div class="wrap">
			<h1><?php esc_html_e( 'Liebherr Interface World – Handbuch', 'liebherr-interface-world' ); ?></h1>

			<h2><?php esc_html_e( 'Warum dieses Werkzeug entstanden ist', 'liebherr-interface-world' ); ?></h2>
			<p><?php esc_html_e( 'Liebherr-Händler, -Lieferanten und -Kunden sind weltweit an unterschiedliche Systeme angebunden. Diese Landingpage macht sichtbar, welche technischen Verbindungen es gibt, in welchem Zustand sie sind, und öffnet zugleich einen öffentlichen Kanal für neue Partneranfragen (Onboarding) – ohne dass technisches Wissen nur in Köpfen statt in der Plattform existiert.', 'liebherr-interface-world' ); ?></p>

			<h2><?php esc_html_e( 'Die vierzehn Bereiche im Überblick', 'liebherr-interface-world' ); ?></h2>

			<h3><?php esc_html_e( '1. Interface Board (§18 – Schnittstellenkatalog)', 'liebherr-interface-world' ); ?></h3>
			<p><?php esc_html_e( 'Jede Schnittstelle wird mit Code, Name, Richtung und Protokoll angelegt und durchläuft den Lebenszyklus draft → in_simulation → verified → approved → retired. Der Status wird seit alpha.31 je Zeile über ein Auswahlfeld gesetzt (Spalte „Status ändern"); jede Änderung wird auditiert. Nur „approved"-Einträge erscheinen in einer öffentlichen Übersicht (§17: strikte Trennung öffentlicher Inhalte von technischen Schnittstellendaten). Capability: liw_manage_interfaces.', 'liebherr-interface-world' ); ?></p>

			<h3><?php esc_html_e( '2. Content Board (§19 – Landingpage-Abschnitte)', 'liebherr-interface-world' ); ?></h3>
			<p><?php esc_html_e( 'Übersicht und Freigabeworkflow für die 14 Landingpage-Abschnitte LP-01…LP-14 (liw_section, Pflichtenheft §8). Titel, Inhalt, Reihenfolge (Feld „Reihenfolge" im Beitrags-Editor) und Revisionen laufen über den nativen WordPress-Editor. Freigabeworkflow Entwurf → Prüfung → freigegeben → veröffentlicht per Statuswechsel-Aktion je Zeile. Grundgerüst (Entscheidung JW 18.09.2026): Drag-and-Drop-Reihenfolge, Zeitsteuerung über den Freigabestatus hinaus, Mehrsprachen-/Geräte-Vorschau, CTA-Ziel-Picker und Medien-Picker-Beschränkung auf freigegebene Bibliothek sind bewusst noch nicht Teil dieser Auslieferung (siehe To-Dos). Layout-Konzept aller 14 Abschnitte: docs/LIW_LANDINGPAGE_KONZEPT.md. Seit alpha.30 zeigt das Board oben eine „Redaktions-Prüfung": sie listet veröffentlichte Abschnitte ohne Titel oder mit Bildern ohne Alt-Text (mit Direktlink zum Bearbeiten) – zu beheben vor dem Launch (§19/§26). Fehlende Übersetzungen prüft später das Sprach-Release-Gate. Capability: liw_manage_content.', 'liebherr-interface-world' ); ?></p>
			<p><?php esc_html_e( 'Standard-Abschnitte anlegen (seit alpha.17): Solange Abschnitte aus dem Pflichtenheft-Bauplan LP-01…LP-14 fehlen, zeigt das Board oben den Knopf „… fehlende Standard-Abschnitte anlegen". Er legt die fehlenden Abschnitte als Entwürfe an – Titel und Reihenfolge (10, 20, … 140) aus dem Pflichtenheft §8, im Inhalt die Redaktionsvorgabe als erster Absatz und bei LP-03/LP-04/LP-06/LP-07/LP-08/LP-11/LP-12/LP-13 der bereits gebaute Baustein als Shortcode-Block. Wurden die Abschnitte bereits vor alpha.19/alpha.20 angelegt, die Shortcode-Blöcke [liw_contact_form] (LP-13), [liw_graphic name="target-model"] (LP-03), [liw_graphic name="magic-cube"] (LP-04) und [liw_graphic name="roadmap"] (LP-12) einmalig von Hand ergänzen (der Knopf legt nur fehlende Abschnitte an, er überschreibt nie). Die Zuordnung läuft über den Code (Spalte „Code"), nicht über den Titel: Titel dürfen frei geändert werden, ein erneuter Klick legt nie Dubletten an und stellt bewusst gelöschte Abschnitte nicht wieder her.', 'liebherr-interface-world' ); ?></p>
			<p><?php esc_html_e( 'Grafiken einbetten (seit alpha.15, erweitert alpha.20): im Abschnitts-Editor einen Shortcode-Block mit [liw_graphic name="…"] einfügen – verfügbar: target-model (Zielbild, LP-03), magic-cube (Magic Cube, LP-04), data-model (Datenmodell, LP-07), process-worlds (Prozesswelten, LP-08), roadmap (Roadmap, LP-12); optional caption="…" für eine Bildunterschrift. Die Grafiken werden inline eingebettet und übernehmen die Farben des zentralen Design Systems. Andere Werte für name werden aus Sicherheitsgründen ignoriert (feste Whitelist, keine Dateipfade).', 'liebherr-interface-world' ); ?></p>

			<h3><?php esc_html_e( '3. Simulation Board (§17 – Magic Cube)', 'liebherr-interface-world' ); ?></h3>
			<p><?php esc_html_e( 'Verwaltet Simulationswelten (liw_simulation_world) und je Welt deren Testszenarien (liw_test_scenario) – Navigation über die URL, ohne Datenänderung. Status-Übergänge (Welt validieren, Szenario bestanden/fehlgeschlagen) sind bewusst noch nicht Teil dieses Boards, da die eigentliche Simulations-Engine fehlt (siehe To-Dos). Capability: liw_manage_interfaces.', 'liebherr-interface-world' ); ?></p>

			<h3><?php esc_html_e( '4. World Connections Map – Datenpflege (§17/LP-06)', 'liebherr-interface-world' ); ?></h3>
			<p><?php esc_html_e( 'Anlage, Freigabe (Öffentlichkeits-Flag) und Statuspflege (geplant/aktiv/inaktiv) von Regionen-Verbindungen für Händler, Lieferanten und Kunden. Nur öffentlich freigegebene Einträge erscheinen auf der Landingpage. Capability: liw_manage_content.', 'liebherr-interface-world' ); ?></p>

			<h3><?php esc_html_e( '5. Onboarding – Partneranfragen (§22)', 'liebherr-interface-world' ); ?></h3>
			<p><?php esc_html_e( 'Öffentliches Formular (Shortcode [liw_onboarding_form], kein Login nötig) für Händler-/Lieferanten-/Kundenanfragen mit Pflicht-Datenschutz-Einwilligung. Jede Anfrage legt einen Partner in der Plattform an (Status „pending"); Freigabe/Ablehnung im Board spiegelt automatisch den Partnerstatus. Die Liste blättert seit alpha.10 seitenweise (20 pro Seite) statt alle Anfragen ungebremst zu laden. Capability: liw_view_onboarding.', 'liebherr-interface-world' ); ?></p>
			<p><?php esc_html_e( 'Partnerkonto anlegen (seit alpha.21, Stufe 1 des geschützten Partnerbereichs): Für eine freigegebene Anfrage erscheint in der Spalte „Partnerkonto" der Knopf „Partnerkonto anlegen". Er legt ein WordPress-Benutzerkonto mit der eigenen Rolle „Liebherr Interface Partner" (liw_partner) an – nur Login/Profil plus Zugang zum Partnerbereich, kein Backend-Zugriff, keine ARALIYA-Hotel- oder Gesundheitsrechte. Das Passwort wird nie erzeugt oder versendet: Der Partner erhält per E-Mail den WordPress-Standardlink zum Setzen seines Passworts. Bewusst kein Automatismus bei Freigabe (zweiter, expliziter Schritt). Existiert zur Kontakt-E-Mail schon ein Benutzer, wird dieser verknüpft und erhält die Partnerrolle zusätzlich. Ein zweiter Klick legt nie ein zweites Konto an. Der geschützte Dokumentenbereich für diese Konten: Abschnitt 7.', 'liebherr-interface-world' ); ?></p>

			<h3><?php esc_html_e( '6. Kontaktanfragen (LP-13 / §22)', 'liebherr-interface-world' ); ?></h3>
			<p><?php esc_html_e( 'Öffentliches Kontaktformular (Shortcode [liw_contact_form], im Abschnitt LP-13 bereits eingebettet) für Projektanfragen von Zentrale, Händlern, Lieferanten, Technologiepartnern und sonstigen Kontakten – bewusst getrennt vom Partner-Onboarding: eine Kontaktanfrage legt keinen Partner an. Felder nach Pflichtenheft §22 (Organisation, Kontaktperson, geschäftliche E-Mail, Telefon, Land/Region, Rolle, lokales ERP/CRM, Projektinteresse als Mehrfachauswahl, Nachricht, getrennte Datenschutz- und Marketing-Einwilligung). Jede Anfrage wird serverseitig validiert, gespeichert, im Einwilligungsprotokoll mit Textversion und Zeitstempel erfasst und per E-Mail an die WordPress-Admin-Adresse gemeldet (bis eine CRM-/Empfängerdefinition vorliegt; per Filter liw_contact_recipients änderbar). Dieses Board zeigt die Anfragen seitenweise mit Status Neu → In Bearbeitung → Abgeschlossen; „Löschen" entfernt Anfrage und Einwilligungen zusammen (§24 Löschprozess). Seit alpha.30 gibt es den Knopf „Als CSV exportieren (§24)": er lädt alle Anfragen als CSV (UTF-8, Excel-freundlich) inklusive Einwilligungen mit Textversion und Zeitstempel; die Datei enthält personenbezogene Daten und ist zweckgebunden, sicher und mit Löschfrist zu behandeln (DSGVO). Capability: liw_view_onboarding.', 'liebherr-interface-world' ); ?></p>

			<h3><?php esc_html_e( '7. Partnerdokumente – geschützter Bereich (§10/§23)', 'liebherr-interface-world' ); ?></h3>
			<p><?php esc_html_e( 'Dokumente, die nur freigegebene Partner sehen dürfen (Stufe 2 des Partnerbereichs, seit alpha.22). Hochladen im Board „Partnerdokumente" (PDF, PNG, JPG, DOCX, max. 10 MB; Dateiname und Inhalt werden geprüft). Die Datei liegt unter zufälligem Namen in einem gesperrten Verzeichnis und ist nie per URL erreichbar – anders als Dateien der Medienbibliothek, die immer öffentlich sind. Anzeige im Frontend über den Shortcode [liw_partner_documents] auf einer eigenen Seite (z. B. „Partnerbereich"): Besucher ohne Login sehen nur einen Login-Link, angemeldete Benutzer ohne Partnerrolle einen Hinweis, Partner die Liste mit Download-Knopf. Jeder Download wird mit Benutzer, Dokument und Zeit protokolliert. „Entfernen" nimmt ein Dokument aus der Liste, die Datei bleibt für den Audit-Trail erhalten. Bitte nur Fassungen hochladen, die Liebherr für Partner freigegeben hat – keine internen Endpunkt- oder Systemnamen ohne Freigabe. Administratoren sehen den Partnerbereich ebenfalls (Prüfung/Support). Capability zum Bereitstellen: liw_manage_content; zum Herunterladen: liw_partner_access.', 'liebherr-interface-world' ); ?></p>

			<h3><?php esc_html_e( '8. Media Board (§18 – Assets & Freigabe)', 'liebherr-interface-world' ); ?></h3>
			<p><?php esc_html_e( 'Bulk-Übersicht der Medienbibliothek: Copyright/Rechteinhaber, Asset-Quelle und CI-005-Freigabe je Medium, ein Speichern-Klick für alle sichtbaren Zeilen. Filter „Alle/Freigegeben/Nicht freigegeben". Seit alpha.10 blätterbar (vorher: hart auf die 50 neuesten Medien begrenzt). Capability: liw_manage_content.', 'liebherr-interface-world' ); ?></p>

			<h3><?php esc_html_e( '9. Brand Board (§10–12 – Design / CI)', 'liebherr-interface-world' ); ?></h3>
			<p><?php esc_html_e( 'Zentrale CI-Tokens der Landingpage (seit alpha.27): Primär-, Sekundär-, Flächen-, Text-, Muted- und Rahmenfarbe, Headline-/Text-Schrift, Radius, Inhaltsbreite und Logo. Diese Werte werden als CSS-Variablen (--brand-*) an alle Frontend-Komponenten ausgegeben, damit keine Markenwerte im Code stehen. Solange kein freigegebenes Liebherr-Brand-Kit vorliegt, gelten bewusst neutrale Fallbacks – es wird kein Liebherr-Logo, keine Liebherr-Farbe erfunden (CI-002). Nach dokumentierter Freigabe hier die Originalwerte eintragen (Referenz: docs/LIW_BRAND_TOKENS.md) und ein Logo auswählen; das Logo muss zuvor im Media Board freigegeben sein, sonst wird es im Frontend nicht ausgegeben (CI-005). Änderungen werden auditiert. Capability: liw_manage_content.', 'liebherr-interface-world' ); ?></p>

			<h3><?php esc_html_e( '10. Header Board (§7 – Navigation & CTAs)', 'liebherr-interface-world' ); ?></h3>
			<p><?php esc_html_e( 'Steuert die Hauptnavigation und die Handlungsaufrufe der Landingpage (Shortcodes [liw_header] und [liw_hero], seit alpha.28). Pflegbar sind: Menüpunkte (je Zeile „Label | Ziel"; Ziel = Anker wie #lp-04, relativer Pfad oder http(s)-URL), Primär-CTA (Standard „Start Integration") und Sekundär-CTA (Standard „Explore the Simulation"), ein optionaler Portal-Login sowie das Hero-Bild (LP-01, Auswahl aus dem Media Board). Der Header klebt oben und wird auf Mobilgeräten zu einem Menü-Umschalter. Das Logo erscheint nur, wenn es im Media Board freigegeben ist – sonst zeigt der Header den Seitennamen als neutrale Wortmarke (CI-002). Änderungen werden auditiert. Capability: liw_manage_content.', 'liebherr-interface-world' ); ?></p>

			<h3><?php esc_html_e( '11. Components Board (§8 – Kern-Komponenten)', 'liebherr-interface-world' ); ?></h3>
			<p><?php esc_html_e( 'Pflegt die Inhalte der drei datengetriebenen Abschnitte (seit alpha.29): Process World Cards (LP-08: Sales, Configuration, Order, Goods, Finance, Service, Warranty), Roadmap-Phasen (LP-12: Contract Model bis Global Rollout) und die neunstufigen Onboarding-Schritte (LP-11). Eingabe je Zeile „Titel | Text"; eine leere Liste stellt die Pflichtenheft-Standardwerte wieder her. Die Ausgabe erfolgt über die Shortcodes [liw_process_worlds], [liw_roadmap] und [liw_onboarding_steps], die die Redaktion in den jeweiligen Abschnitt einfügt. Rein textbasiert, damit barrierearm. Änderungen werden auditiert. Capability: liw_manage_content.', 'liebherr-interface-world' ); ?></p>

			<h3><?php esc_html_e( '12. Audit Board (§18/SEC-005 – Nachvollziehbarkeit)', 'liebherr-interface-world' ); ?></h3>
			<p><?php esc_html_e( 'Unveränderliche Lese-Ansicht aller administrativen Änderungen in Interface World seit alpha.31 (Anlegen, Statuswechsel, Freigaben, CSV-Exporte …), mit Zeitpunkt, Aktion, Objekt, Objekt-ID, Akteur und Akteurstyp – seitenweise. Die Daten stammen aus dem zentralen, unveränderlichen ARALIYA-Audit-Log und werden auf dieses Modul gefiltert; hier wird nichts geändert oder gelöscht. Capability: liw_manage_interfaces.', 'liebherr-interface-world' ); ?></p>

			<h3><?php esc_html_e( '13. Language Board (§20/§21 – Release-Readiness, LANG-006)', 'liebherr-interface-world' ); ?></h3>
			<p><?php esc_html_e( 'Zeigt seit alpha.32 je aktiver Sprache, wie vollständig die öffentlichen Flächen (veröffentlichte Abschnitte + Trägerseite) übersetzt sind – wie viele Flächen vollständig sind, den Mindest-Übersetzungsgrad und ob die Sprache release-fähig ist (LANG-006: alle Pflichtsegmente übersetzt, nichts veraltet, kritische Segmente freigegeben). Die Zahlen stammen aus dem zentralen Übersetzungssystem. Kuratierung und Freigabe der Texte selbst erfolgen im ARALIYA Languages Hub; das endgültige „harte" Freischalten einer Sprache ist eine Betriebsentscheidung. UI-Texte (Navigation, CTAs, Formular, Fehlermeldungen) laufen über Sprachdateien/Slots und werden dort gepflegt. SEO je Sprache (hreflang, Canonical mit Sprachparameter, Open-Graph-Tags) erzeugt das Modul automatisch; Abschnitts-Fragmente bleiben aus der Sitemap heraus (kanonisch ist die Landingpage). Capability: liw_manage_content.', 'liebherr-interface-world' ); ?></p>

			<h3><?php esc_html_e( '14. Landingpage im Frontend – Shortcodes & Design System', 'liebherr-interface-world' ); ?></h3>
			<p><?php esc_html_e( 'Die zusammengesetzte Landingpage (seit alpha.18): eine normale WordPress-Seite anlegen (z. B. „Interface World"), einen Shortcode-Block mit [liw_landingpage] einfügen und veröffentlichen. Der Shortcode zeigt alle Abschnitte mit Status „Veröffentlicht" in ihrer Reihenfolge untereinander – Entwürfe, Abschnitte in Prüfung und freigegebene, aber noch nicht veröffentlichte Abschnitte bleiben unsichtbar. Der Freigabeworkflow im Content Board steuert also direkt, was öffentlich erscheint. In den Abschnitten eingebettete Bausteine (Grafiken, World Connections Map, Onboarding-Formular) werden dabei aufgelöst. Jeder Abschnitt erhält einen Anker aus seinem Code (z. B. #lp-07). Mehrsprachigkeit (seit alpha.24): Die Sprachsteuerung des Core (Cookie und ?lang=de|en|pl) gilt auch für Landingpage und Abschnitte – Titel und Inhalte kommen aus der Core-Übersetzung. Den Sprachumschalter des Core setzt die Redaktion per Shortcode [liw_language_switcher] ein (z. B. im Header oder Abschnitt LP-14). Suchmaschinen erhalten auf der Trägerseite hreflang-Alternativen je Sprache; sobald der Core-Sprach-Router mit /en/-URLs aktiv ist, übernimmt dieser automatisch. Datenschutz-Einwilligungen werden mit Textversion inklusive Sprache protokolliert (§24). Seit alpha.23 zeigt die Seite oben eine klebende Sprungleiste mit allen veröffentlichten Abschnitten (erscheint ab zwei Abschnitten); [liw_landingpage nav="0"] schaltet sie ab. Seit alpha.26 wird in dieser Sprungleiste beim Scrollen automatisch der gerade sichtbare Abschnitt hervorgehoben (Akzentfarbe + Unterstrich), damit Besucher jederzeit sehen, wo auf der Seite sie sich befinden; das geschieht über ein kleines Zusatzskript und ist reine Anzeige – ohne JavaScript funktioniert die Sprungleiste unverändert. Solange nichts veröffentlicht ist, sehen nur angemeldete Redakteure einen Hinweis, Besucher sehen nichts.', 'liebherr-interface-world' ); ?></p>
			<p><?php esc_html_e( 'Öffentlicher Shortcode [liw_world_connections_map] zeigt freigegebene Verbindungen gruppiert nach Region (Regionen-Grid, keine geografische Karte – siehe To-Dos). Alle Frontend-Shortcodes ([liw_landingpage], [liw_onboarding_form], [liw_contact_form], [liw_world_connections_map], [liw_graphic], [liw_partner_documents], [liw_language_switcher]) werden ausschließlich über die zentralen ARALIYA-Design-Tokens gestaltet (assets/css/liebherr-frontend.css), keine eigenen Markenfarben. Das Stylesheet lädt nur auf Seiten, die einen dieser Shortcodes tatsächlich enthalten.', 'liebherr-interface-world' ); ?></p>

			<h2><?php esc_html_e( 'Nachvollziehbarkeit: Programmierlogbuch und To-Dos', 'liebherr-interface-world' ); ?></h2>
			<p><?php esc_html_e( 'Der Reiter „🧾 Programmierlogbuch" listet jede Quellcodeänderung auf Datei-/Klassenebene (was wurde wann geändert). Der Reiter „📋 To-Dos" listet offene bzw. bewusst zurückgestellte Punkte mit Quellenangabe (z. B. Content Board §19, echte Karte für die World Connections Map, Docker-Praxistest). Beide werden bei jeder Aufgabe gepflegt, in der sich etwas ändert.', 'liebherr-interface-world' ); ?></p>

			<h2><?php esc_html_e( 'FAQ', 'liebherr-interface-world' ); ?></h2>
			<p><strong><?php esc_html_e( 'Warum sehe ich in einem Board keine Einträge?', 'liebherr-interface-world' ); ?></strong><br />
			<?php esc_html_e( 'Entweder wurden noch keine Datensätze angelegt, oder Ihrer Rolle fehlt die jeweilige Capability (liw_manage_interfaces, liw_manage_content oder liw_view_onboarding – siehe Abschnitt oben).', 'liebherr-interface-world' ); ?></p>
			<p><strong><?php esc_html_e( 'Warum sind manche Onboarding-Anfragen bzw. Medien plötzlich auf Seite 2?', 'liebherr-interface-world' ); ?></strong><br />
			<?php esc_html_e( 'Seit alpha.10 blättern beide Listen (20 bzw. 50 Einträge pro Seite), statt alle Datensätze auf einmal zu laden – Performance-Schutz bei wachsender Nutzung.', 'liebherr-interface-world' ); ?></p>

			<h2><?php esc_html_e( 'Technische Details', 'liebherr-interface-world' ); ?></h2>
			<p><?php esc_html_e( 'Tabellen: liw_interface, liw_simulation_world, liw_test_scenario, liw_connection, liw_consent_log, liw_partner_extra. Das Plugin setzt araliya-platform-core voraus und nutzt dessen Übersetzungs-, Rollen-, Audit-, SEO-, Medien-, Partner- und Markdown-Renderer-Services ausschließlich über den CoreBridge-Adapter (src/CoreBridge/) – nie direkt. Details siehe docs/ADR-LIW-001 und docs/LIW_PROGRAMMIERLOGBUCH.md.', 'liebherr-interface-world' ); ?></p>

			<p><em><?php esc_html_e( 'Dieses Handbuch wird mit jeder fachlichen Erweiterung des Moduls fortgeschrieben.', 'liebherr-interface-world' ); ?></em></p>
		</div>
		<?php
	}
}
